ARG        BASE
FROM       ${BASE}

ADD --chown=${QDB_USER}:${QDB_GROUP} {{ env.qdb_api_c_url }} /opt/qdb/
ADD --chown=${QDB_USER}:${QDB_GROUP} {{ env.qdb_api_rest_url }} /opt/qdb/
RUN    cd /opt/qdb                    \
    && find . -name "*.tar.gz" -exec tar -xvzf {} \; \
    && rm -f ./*.tar.gz

COPY docker-wrapper.sh /docker-wrapper.sh

ENTRYPOINT ["/docker-wrapper.sh"]
