# Per k8s docs, define headless service for identity of pods.
# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
# https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
apiVersion: v1
kind: Service
metadata:
  name: qdb-hs
  labels:
    app: qdb
spec:
  ports:
  - port: 2836
    name: client
  - port: 2837
    name: control
  clusterIP: None
  selector:
    app: qdb

---

# Clients should use this service to connect
apiVersion: v1
kind: Service
metadata:
  name: qdb-cs
  labels:
    app: qdb
spec:
  ports:
  - port: 2836
    name: client
  - port: 2837
    name: control
  selector:
    app: qdb

---

# create secret:
# kubectl create secret generic qdb-secrets --from-file=/my/path/to/quasardb.key
#
# log in:
# kubectl run --generator=run-pod/v1 -ti qdbsh --image=bureau14/qdbsh:3.6 -- --cluster qdb://qdb-cs:2836/

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quasardb

spec:
  selector:
    matchLabels:
      app: qdb

  serviceName: qdb-hs
  replicas: 3
  podManagementPolicy: OrderedReady

  template:
    metadata:
      labels:
        app: qdb

    spec:
      volumes:
      - name: secrets
        secret:
          secretName: qdb-secrets
      containers:
      - name: qdbd
        image: bureau14/qdb:3.6
        imagePullPolicy: "Always"
        ports:
          - containerPort: 2836
            name: client
          - containerPort: 2837
            name: control
        resources:
          limits:
            memory: "2Gi"
        volumeMounts:
          - name: datadir
            mountPath: /opt/qdb/depot
          - name: secrets
            mountPath: "/var/secret/"
            readOnly: true
        env:
          - name: QDB_LICENSE_FILE
            value: "/var/secret/qube.key"
          - name: K8S_REPLICA_COUNT
            value: "3"

        readinessProbe:
          tcpSocket:
            port: 2836
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 2836
          initialDelaySeconds: 15
          periodSeconds: 20

      securityContext:
        runAsUser: 999
        fsGroup: 999

  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      volumeMode: Filesystem
      resources:
        requests:
          storage: 10Gi
      storageClassName: manual
