ARG        BASE
FROM       ${BASE} AS build
ARG        BASE

ADD --chown=qdb:qdb {{ env.qdb_utils_url }} /opt/qdb/
RUN cd /opt/qdb && tar -xzvf ./*.tar.gz

FROM       ${BASE}
COPY --chown=qdb:qdb --from=build /opt/qdb/bin/qdbsh /opt/qdb/bin/qdbsh

ENTRYPOINT ["/opt/qdb/bin/qdbsh"]
